import { useMutation } from "@tanstack/react-query"
import { useRouter } from "next/router"
import { SubmitHandler, useForm } from "react-hook-form"

// This page is for example!
// TODO: Fetch functions will be in separated folder most probably called services
// They will be autogenerated as well

// TODO: Login page too...

const fetchUser = (data: unknown) => {
  return fetch("http://localhost:8080/users", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  })
}

type RegisterRequest = {
  username: string
  email: string
  password: string
}

const Auth = () => {
  const router = useRouter()

  const { register, handleSubmit } = useForm<RegisterRequest>()
  const { mutate } = useMutation({
    mutationFn: (data: RegisterRequest) => fetchUser(data),
    onSuccess: () => {
      // TODO: Toast, or something indicates registered successfully!
      console.log("success")
      router.push("/")
    },
  })

  return (
    <div>
      <form onSubmit={handleSubmit(mutate as SubmitHandler<RegisterRequest>)}>
        <div>
          <label htmlFor="username">Username</label>
          <input {...register("username")} />
        </div>
        <div>
          <label htmlFor="username">Email</label>
          <input {...register("username")} />
        </div>
        <div>
          <label htmlFor="username">Password</label>
          <input type="password" {...register("username")} />
        </div>
        <input type="submit" />
      </form>
    </div>
  )
}

export default Auth
