version: "3.8"
services:
  quizaction-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=quizaction
    container_name: quizaction-db
    ports:
      - 5432:5432
  quizaction-backend:
    build:
      context: ./server
      dockerfile: "Dockerfile.dev"
    container_name: quizaction-backend
    environment:
      HTTP_PORT: "80"
      LOG_LEVEL: "debug"
      POSTGRES_CONNSTRING: postgresql://root:secret@quizaction-db/quizaction?sslmode=disable
      CORS_ALLOW_ORIGINS: http://localhost:3000
    ports:
      - 8080:80
    depends_on:
      - quizaction-db
    volumes:
      - ./server/:/app
  quizaction-frontend:
    build:
      context: ./client
      dockerfile: "Dockerfile.dev"
    container_name: quizaction-frontend
    environment:
      PORT: 3000
      BACKEND_URL: http://quizaction-backend:80
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
    ports:
      - 3000:3000
    volumes:
      - ./client/:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next

volumes:
  frontend_node_modules:
  frontend_next:
